"""Admission-gate bench on corpora that are NOT ours (2026-07-20).

Round-1 review (Kimi): "75% quarantined = any customer's trajectory" is
induction on n=1 — our corpus, our agent, our exhaust. This measures the
0.7.0 default gate on foreign material:

  (a) two LABELED corpora from OTHER domains, adversarially generated by
      the review models themselves (personal-assistant by GLM-5.2,
      dev-agent/customer-support by Kimi-K3), each salted with trap
      topics — legitimate knowledge under telemetry-looking names
      (metric/kpi-churn as a KPI definition, bus/orari as bus schedules)
      and intentional-JSON knowledge (a documented webhook schema);
  (b) real external datasets (TruthfulQA heldout claims, HaluEval
      answers) as knowledge-only natural text: the topic is neutral, so
      any non-accept verdict is a CONTENT-detector false positive
      (injection / markup) that would hit a real QA customer.

Provenance is neutralized (source_episodes given) to isolate the routing
and content detectors from the low-provenance flag. Duplicate detection
is off (None seen_norms): dataset-internal repeats are not the subject.

Usage: python scripts/bench_admission_external_corpora.py \
           <personal.jsonl> <devagent.jsonl>
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from verimem.admission_gate import ROUTE_TELEMETRY, classify_admission  # noqa: E402

EXTERNAL = REPO / "benchmark" / "data" / "external"


def load_generated(path: Path) -> list[dict]:
    """Tolerant JSONL: keep lines that parse and carry the 3 keys."""
    items = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip().strip("`")
        if not line.startswith("{"):
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if {"topic", "proposition", "label"} <= set(row):
            items.append(row)
    return items


def classify(topic: str, text: str) -> str:
    return classify_admission(
        topic=topic, proposition=text, status="model_claim",
        writer_role="agent_inference", source_episodes=["src"],
    ).decision


def eval_labeled(name: str, items: list[dict]) -> dict:
    know = [i for i in items if i["label"] == "knowledge"]
    tele = [i for i in items if i["label"] == "telemetry"]
    k_dec = Counter(classify(i["topic"], i["proposition"]) for i in know)
    t_dec = Counter(classify(i["topic"], i["proposition"]) for i in tele)
    fp = [i["topic"] for i in know
          if classify(i["topic"], i["proposition"]) == ROUTE_TELEMETRY]
    out = {
        "corpus": name, "n": len(items),
        "knowledge_n": len(know), "telemetry_n": len(tele),
        "knowledge_decisions": dict(k_dec),
        "telemetry_decisions": dict(t_dec),
        "knowledge_routed_FP": len(fp),
        "knowledge_routed_FP_topics": fp,
        "telemetry_routed_recall": (
            round(t_dec[ROUTE_TELEMETRY] / len(tele), 3) if tele else None),
    }
    return out


def eval_external_knowledge(name: str, texts: list[str]) -> dict:
    dec = Counter(classify("knowledge/qa", t) for t in texts)
    flagged = [t[:110] for t in texts
               if classify("knowledge/qa", t) not in ("accept",)]
    return {
        "corpus": name, "n": len(texts), "decisions": dict(dec),
        "non_accept_examples": flagged[:8],
    }


def main() -> None:
    results = []
    for arg, label in zip(sys.argv[1:3], ("personal", "devagent"),
                          strict=False):
        items = load_generated(Path(arg))
        results.append(eval_labeled(label, items))

    tq = [json.loads(x) for x in
          (EXTERNAL / "truthfulqa_pairs_heldout.jsonl").read_text(
              encoding="utf-8").splitlines() if x.strip()]
    tq_texts = [r["claim"] for r in tq if r.get("label") == 1]
    results.append(eval_external_knowledge("truthfulqa_heldout_true_claims",
                                           tq_texts))

    he = [json.loads(x) for x in
          (EXTERNAL / "halueval_qa_heldout.jsonl").read_text(
              encoding="utf-8").splitlines() if x.strip()]
    he_texts = [r.get("right_answer") or r.get("answer") or r["knowledge"]
                for r in he]
    results.append(eval_external_knowledge("halueval_heldout_answers",
                                           he_texts))

    out = REPO / "benchmark" / "results" / "admission_external_2026-07-20.json"
    out.write_text(json.dumps(results, indent=2, ensure_ascii=False),
                   encoding="utf-8")
    print(json.dumps(results, indent=2, ensure_ascii=False))
    print("WRITTEN=" + str(out))


if __name__ == "__main__":
    main()
