"""F2 — module inventory + test mapping (task #23, the map's skeleton).

For every engram module: LOC, docstring first line (what it says it does),
which test files reference it, and how many test functions those contain.
Modules with ZERO test references are the verification gaps F2 must close
or consciously retire ("pulizia"). Pure static analysis — no imports of the
modules themselves (safe on a dirty tree), no network, no model.

Output: docs/F2_MODULE_INVENTORY.md (sorted: gaps first, then by LOC).
"""
from __future__ import annotations

import ast
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "engram"
TESTS = ROOT / "tests"
OUT = ROOT / "docs" / "F2_MODULE_INVENTORY.md"


def first_doc_line(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
        doc = ast.get_docstring(tree) or ""
        return doc.strip().splitlines()[0][:110] if doc.strip() else "(no docstring)"
    except SyntaxError:
        return "(syntax error!)"


def count_test_funcs(path: Path) -> int:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError:
        return 0
    return sum(1 for n in ast.walk(tree)
               if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
               and n.name.startswith("test_"))


def main() -> int:
    modules = sorted(p for p in PKG.rglob("*.py")
                     if "__pycache__" not in p.parts)
    test_files = sorted(p for p in TESTS.rglob("test_*.py")
                        if "__pycache__" not in p.parts)

    # map module -> test files that mention it (import or dotted use)
    refs: dict[str, list[tuple[str, int]]] = defaultdict(list)
    test_meta: dict[str, int] = {}
    for tf in test_files:
        text = tf.read_text(encoding="utf-8", errors="replace")
        test_meta[tf.name] = count_test_funcs(tf)
        for m in modules:
            rel = m.relative_to(PKG).with_suffix("")
            dotted = ".".join(("engram", *rel.parts))
            stem = rel.parts[-1]
            if stem == "__init__":
                continue
            pat = (rf"(?:from\s+{re.escape(dotted)}\s+import|"
                   rf"import\s+{re.escape(dotted)}\b|"
                   rf"from\s+engram(?:\.\w+)*\s+import\s+[^\n]*\b{re.escape(stem)}\b|"
                   rf"\bengram\.{re.escape(stem)}\b)")
            if re.search(pat, text):
                refs[str(m)].append((tf.name, test_meta[tf.name]))

    rows = []
    for m in modules:
        rel = m.relative_to(PKG)
        if rel.name == "__init__.py":
            continue
        loc = sum(1 for line in m.read_text(
            encoding="utf-8", errors="replace").splitlines() if line.strip())
        r = refs.get(str(m), [])
        rows.append({
            "module": str(rel).replace("\\", "/"),
            "loc": loc,
            "doc": first_doc_line(m),
            "n_test_files": len(r),
            "n_test_funcs": sum(c for _, c in r),
            "tests": ", ".join(sorted(n for n, _ in r))[:200],
        })

    gaps = [r for r in rows if r["n_test_files"] == 0]
    covered = [r for r in rows if r["n_test_files"] > 0]
    gaps.sort(key=lambda r: -r["loc"])
    covered.sort(key=lambda r: -r["loc"])

    total_loc = sum(r["loc"] for r in rows)
    gap_loc = sum(r["loc"] for r in gaps)

    lines = [
        "# F2 — Module inventory & test map (auto-generated)",
        "",
        f"Generated by `scripts/f2_module_inventory.py`. Modules: **{len(rows)}** "
        f"({total_loc:,} LOC) · test files: **{len(test_files)}** "
        f"({sum(test_meta.values()):,} test functions) · "
        f"**modules with ZERO test references: {len(gaps)}** ({gap_loc:,} LOC, "
        f"{100*gap_loc/max(1,total_loc):.0f}% of the package).",
        "",
        "Reference-based mapping (imports/dotted use), not line coverage — a",
        "module can be referenced and still poorly tested; this is the SKELETON",
        "for the layer-by-layer verification, not its verdict.",
        "",
        "## ⚠️ Verification gaps (no test file references the module)",
        "",
        "| module | LOC | first docstring line |",
        "|---|---|---|",
    ]
    for r in gaps:
        lines.append(f"| `{r['module']}` | {r['loc']} | {r['doc']} |")
    lines += [
        "",
        "## Covered modules (by size)",
        "",
        "| module | LOC | test files | test fns | first docstring line |",
        "|---|---|---|---|---|",
    ]
    for r in covered:
        lines.append(
            f"| `{r['module']}` | {r['loc']} | {r['n_test_files']} | "
            f"{r['n_test_funcs']} | {r['doc']} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"modules={len(rows)} loc={total_loc:,} gaps={len(gaps)} "
          f"gap_loc={gap_loc:,} ({100*gap_loc/max(1,total_loc):.0f}%)")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
